[book]
authors = ["David A. Samson"]
language = "en"
multilingual = false
src = "src"
title = "The Dewy Programming Language"

[build]
build-dir = "book"

[output.html]
additional-js = ['dewy_online_interpreter_handler.js']